### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by chycken** [roflmuffin/CounterStrikeSharp#63] opened 2023-11-11 18:50 UTC
Hello,
Can you add admin menu?
I know that cs2 doesnt have menu yet like csgo, but im thinking of that if i say !admin, than a menu appears in the chat (just like in the mini admin plugin), which show me that !1 slay !2 slap !3 kick etc....

**Comment by ItsChase88** [comment] 2023-11-11 19:13
This has already been built into CSS.
https://github.com/roflmuffin/CounterStrikeSharp/blob/main/managed/CounterStrikeSharp.API/Modules/Menu/ChatMenu.cs

**Comment by crashzk** [comment] 2023-11-11 20:29
This is already being discussed on Discord: https://discord.com/channels/1160907911501991946/1172518338979704853

In short, so far there is no way to leave it the same as CSGO, CS2 removed it.

**Comment by chycken** [comment] 2023-11-11 20:42
it doesn't have to be like it was in csgo. I meant to create an admin menu in the chat, so that there is no need for a separate plugin (for ex. mini admin). 
So we can type !admin in the chat and it will list all available chat commands like !ban !kick...

**Comment by roflmuffin** [comment] 2023-11-13 03:50
Im closing this issue as it is too ambiguous and likely a duplicate of #41

**Closed by roflmuffin** 2023-11-13 03:50 UTC
