### ISSUE TITLE
undefined symbol: AssertValidStringPtr

### ISSUE THREAD

**Issue by crywolfy** [roflmuffin/CounterStrikeSharp#609] opened 2024-10-06 10:02 UTC
@Solved, sorry, ive uploaded Windows Version on Linux server.

Hi there , does anyone has this problem too ? at start

`
_[META] Failed to load plugin addons/counterstrikesharp/bin/linuxsteamrt64/counterstrikesharp: /home/container/game/csgo/addons/counterstrikesharp/bin/linuxsteamrt64/counterstrikesharp.so: undefined symbol: AssertValidStringPtr`
_

Listing 2 plugins:
  [01] Fake RCON (1.2.1c) by Kriax
  [02] ERROR

meta version
 Metamod:Source Version Information
    Metamod:Source version 2.0.0-dev+1314
    Plugin interface version: 16:14
    SourceHook version: 5:5
    Loaded As: GameDLL (gameinfo.txt)
    Compiled on: Oct  3 2024 15:12:54
    Built from: https://github.com/alliedmodders/metamod-source/commit/557121c
    Build ID: 1314:557121c
    http://www.metamodsource.net/

version  : 1.40.3.3/14033 10203 secure  public

CounterStrikeSharp v276 , last at the moment, was compiled 5 hrs ago.

@Solved, sorry, ive uploaded Windows Version on Linux server.

**Comment by KillStr3aK** [comment] 2024-10-06 10:17
duplicate of #587

**Closed** 2024-10-06 10:20 UTC
Labels: untriaged
