### ISSUE TITLE
Attempting to read CCSPlayer_ViewModelServices.ViewModel throws System.Reflection.TargetInvocationException

### ISSUE THREAD

**Issue by b0ink** [roflmuffin/CounterStrikeSharp#60] opened 2023-11-11 13:06 UTC
I'm attempting to get the player's view model

[server.hpp schema](https://github.com/neverlosecc/source2sdk/blob/a099bcd264b75f60eeaca79c348627081b951c19/sdk/server.hpp#L8449C1-L8454C3)
```hpp
class CCSPlayer_ViewModelServices : public CPlayer_ViewModelServices
{
public:
	// MNetworkEnable
	CHandle< CBaseViewModel > m_hViewModel[3]; // 0x40	
};
```

What i've attempted in c# plugin:
```cs
var ViewModelServices = new CCSPlayer_ViewModelServices(this.PlayerPawn.Value.ViewModelServices.Handle);
var viewModelArray = ViewModelServices.ViewModel; // line "68"
```
but receive the following error:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: Cannot use type 'CounterStrikeSharp.API.Modules.Utils.CHandle`1[CounterStrikeSharp.API.Core.CBaseViewModel]'. Only value types without pointers or references are supported.
   at CounterStrikeSharp.API.Modules.Memory.Schema.GetFixedArray[T](IntPtr pointer, String className, String memberName, Int32 count) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Modules/Memory/Schema.cs:line 69
   at CounterStrikeSharp.API.Core.CCSPlayer_ViewModelServices.get_ViewModel() in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Objects.g.cs:line 7576
   at <my function name> in <my file name>.cs:line 68
```

i've tried various null checks and tried using `Server.NextFrame` to access the different properties but all leads to the same exception

**Comment by a0w89fwa0f** [comment] 2023-11-13 04:12
Also having this same issue with similar code, have tried various things but always get the same error in the original post.

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
```

My Code:
```C#
public static CCSPlayer_ViewModelServices? GetCCSPlayer_ViewModelServices(CCSPlayerPawn pLocalPawn)
{
    if (pLocalPawn.ViewModelServices == null)
    {
        return null;
    }

    CCSPlayer_ViewModelServices pViewModelServices = new CCSPlayer_ViewModelServices(pLocalPawn.ViewModelServices.Handle);

    if (pViewModelServices == null)
    {
        return null;
    }

    return pViewModelServices;
}

[ConsoleCommand("test")]
public void OnCommand(CCSPlayerController? pLocalPlayerController, CommandInfo pCommandInfo)
{
    if (pLocalPlayerController == null) return;

    CCSPlayerPawn pLocalPawn = pLocalPlayerController.PlayerPawn.Value;

    if (pLocalPawn == null) return;

    CPlayer_WeaponServices? pWeaponServices = pLocalPawn.WeaponServices;

    if (pWeaponServices == null) return;

    CCSPlayer_ViewModelServices? pViewModelServices = GetCCSPlayer_ViewModelServices(pLocalPawn);

    if (pViewModelServices == null) return;

    CHandle<CBaseViewModel> pViewModel = pViewModelServices.ViewModel[0];

    if (pViewModel == null) return;
}
```

The line that causes the error in particular is this:
```C#
CHandle<CBaseViewModel> pViewModel = pViewModelServices.ViewModel[0];
```

**Comment by KillStr3aK** [comment] 2023-11-19 13:50
Hi, there was a discussion about this on discord and the "general problem" will be fixed a bit later on as I'm busy with other things currently.

However, there is a workaround for this (and similar cases)
You can do the following:

```csharp
public unsafe T[] GetFixedArray<T>(nint pointer, string @class, string member, int length) where T: NativeObject
{
    nint ptr = pointer + Schema.GetSchemaOffset(@class, member);
    Span<nint> references = MemoryMarshal.CreateSpan<nint>(ref ptr, length);
    T[] values = new T[length];

    for (int i = 0; i < length; i++)
    {
        values[i] = (T)Activator.CreateInstance(typeof(T), references[i])!;
    }

    return values;
}

public unsafe CHandle<CBaseViewModel>[] GetPlayerViewModels(CCSPlayerController player)
{
    CCSPlayer_ViewModelServices viewModelServices = new CCSPlayer_ViewModelServices(player.PlayerPawn.Value.ViewModelServices!.Handle);
    return GetFixedArray<CHandle<CBaseViewModel>>(viewModelServices.Handle, "CCSPlayer_ViewModelServices", "m_hViewModel", 3);
}
```

**Comment by roflmuffin** [comment] 2024-02-22 04:45
Duplicate of #134

**Closed by roflmuffin** 2024-02-22 04:45 UTC
