### ISSUE TITLE
[BUG] Command removal problem when a "handler" has multiple "name"

### ISSUE THREAD

**Issue by K4ryuu** [roflmuffin/CounterStrikeSharp#301] opened 2024-01-31 20:09 UTC
Hey
I've managed to find the solution for the problem, when you register multiple command to the same handler, none (or maybe only the last(?)) gets removed when the plugin unloads. Without the solution, after every hotReload the command replies +1 times. So if you reload the plugin 13 times, it is going to send 13 replies from the old plugins and one from the current.

With the "name" and "handler" I'm referencing to the BasePlugin.cs AddCommand section

Reproduce:
```c#
commands.RankCommands.ForEach(commandString =>
{
	plugin.AddCommand($"css_{commandString}", "Check the current rank and points", OnCommandRank);
});
```
This problem also appears if you use lambda.

Solution:
```c#
private CommandInfo.CommandCallback CallbackAnonymizer(Action<CCSPlayerController?, CommandInfo> action)
{
    return new CommandInfo.CommandCallback(action);
}

commands.RankCommands.ForEach(commandString =>
{
    AddCommand($"css_{commandString}", "Check the current rank and points", CallbackAnonymizer(ModuleRank.OnCommandRank));
});
```

This could be done in BasePlugin.cs also to let every command be deleted upon plugin unload.

**Comment by roflmuffin** [comment] 2024-02-01 01:09
I think this is a duplicate of #53 since the unload logic is the same

**Comment by K4ryuu** [comment] 2024-02-01 10:42
It is probably enough to modify the AddCommand also to use new CommandCallback(action) and that solves the duplicates and let it delete properly. However modifying the RemoveCommand to not to delete the handler after the first find could be also work.

**Closed** 2024-02-19 08:29 UTC
