### ISSUE TITLE
Admin rights not working

### ISSUE THREAD

**Issue by asapverneri** [roflmuffin/CounterStrikeSharp#182] opened 2023-12-07 14:47 UTC
I'm having an issue with my cs2 windows dedicated server where i'm using daffyyyy's CS2-SimpleAdmin plugin.
I reached out to daffyyyy and we made sure that it's not plugin issue.
The problem is that i don't have permission to use admin rights. All commands works throught game server's console tho.
However typing css_admins_list to server's console it shows that i'm an admin.
I've tried using group instead of flags and Steamid64 as identity, but those changes doesn't make any difference.

I'm currently running latest cssharp (v112) and my admins.json looks like this:
```
{
  "yay": {
    "identity": "STEAM_0:0:XXXXXXXX",
	"immunity": 100,
	"flags": [
      "@css/reservation",
      "@css/generic",
      "@css/kick",
      "@css/ban",
      "@css/unban",
      "@css/vip",
      "@css/slay",
      "@css/changemap",
      "@css/cvar",
      "@css/config",
      "@css/chat",
      "@css/vote",
      "@css/password",
      "@css/rcon",
      "@css/cheats",
      "@css/root",
      "@resetscore/admin"
    ]
  }
}
```

**Comment by KillStr3aK** [comment] 2023-12-07 15:07
probably worth waiting for #143 to be merged and ensure that the issue is still persists

**Comment by roflmuffin** [comment] 2023-12-08 02:36
Please try again on build 115 if you are using Windows.

**Comment by asapverneri** [comment] 2023-12-08 21:37
Works with v115. Problem solved i guess :)

**Closed** 2023-12-09 01:05 UTC
