### ISSUE TITLE
Problems with server starting on Ubuntu 23.10 "Mantic Minotaur"

### ISSUE THREAD

**Issue by equaerdist** [roflmuffin/CounterStrikeSharp#460] opened 2024-05-24 00:36 UTC
GameTypes: missing mapgroupsSP entry for game type/mode (cooperative/coopmission).
[03:33:16.522] CSSharp: Initializing
[03:33:16.523] CSSharp: CoreConfig loaded.
[03:33:16.590] CSSharp: Copying bytes from disk for /home/steam/steamcmd/cs_go/game/bin/linuxsteamrt64/libengine2.so
[03:33:16.890] CSSharp: Copying bytes from disk for /home/steam/steamcmd/cs_go/game/bin/linuxsteamrt64/../../csgo/bin/linuxsteamrt64/libserver.so
[03:33:16.958] CSSharp: Globals loaded.
[03:33:16.959] CSSharp: Failed to find signature for 'Host_Say'
Im tried to edit gamedata.json host_say signature myself, im add \\x, which saw in already posted related issues, but it doesnt work for me. Any ideas? Thank you.

**Comment by pimpmyname2** [comment] 2024-05-24 00:47
It happens for me aswell, CSS was working fine yesterday before the new update for CS2

**Comment by mstankov** [comment] 2024-05-24 01:14
Duplicate of https://github.com/roflmuffin/CounterStrikeSharp/issues/459

**Comment by crashzk** [comment] 2024-05-24 01:24
Wait for an update from CSSharp.

**Comment by Jano1959** [comment] 2024-05-24 13:06
#me2 
Instance not starting unless I disable this Addon.

Could be it happened after latest CS2 update.

Running instances in AMP.

Console dumps:

`
Network System Initialized
L 05/24/2024 - 12:37:26: server_cvar: "phys_implicit_integarator" "true"
 failed to dlopen "/AMP/counter-strike2/730/game/bin/linuxsteamrt64/libserver_valve.so" error=/AMP/counter-strike2/730/game/bin/linuxsteamrt64/libserver_valve.so: cannot open shared object file: No such file or directory
L 05/24/2024 - 12:37:26: server_cvar: "phys_drag_multiplier" "1.000000"
 failed to dlopen "libserver_valve.so" error=libserver_valve.so: cannot open shared object file: No such file or directory
L 05/24/2024 - 12:37:26: server_cvar: "phys_buoyancy_vertical_damping_multiplier" "1.000000"
L 05/24/2024 - 12:37:26: server_cvar: "phys_buoyancy_angular_damping_multiplier" "1.000000"
L 05/24/2024 - 12:37:26: server_cvar: "phys_buoyancy_drag_multiplier" "1.000000"
L 05/24/2024 - 12:37:26: server_cvar: "phys_buoyancy_max_acceleration" "3200.000000"
MOD desires lightbiner GPU but is unsupported by HW (SupportsCompute=0 CubeMapArrays=0)
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libserver_valve.so, got (nil)
 failed to dlopen /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libserver_valve.so error=/AMP/counter-strike2/730/game/bin/linuxsteamrt64/libserver_valve.so: cannot open shared object file: No such file or directory
Loaded libserver_valve.so, got (nil)
 failed to dlopen libserver_valve.so error=libserver_valve.so: cannot open shared object file: No such file or directory
Loaded /AMP/counter-strike2/730/game/csgo/addons/metamod/bin/linuxsteamrt64/libserver.so, got 0x562877c5a490
`

`
14.37.19
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libengine2.so, got 0x5616c5a53e80
Setting breakpad minidump AppID = 2347773
Console initialized.
Steam AppId(730), BreakpadId(2347771)
InitSteamLogin_Internal: Skipping initializing breakpad.
Steam Universe is invalid, possibly asking before Steam was successfully initialized.
ResetBreakpadAppId: Universe is 0 (k_EUniverseInvalid)
ResetBreakpadAppId: Setting dedicated server app id: 2347773
Loaded libSDL3.so.0, got 0x5616c5a9ab80
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libtier0.so, got 0x5616c5a35630
Visibility enabled.
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libfilesystem_stdio.so, got 0x5616c5a9bbb0
USRLOCAL path not found!
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/liblocalize.so, got 0x5616c5aae340
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/librendersystemempty.so, got 0x5616c5aae950
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libresourcesystem.so, got 0x5616c5aaf4e0
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libschemasystem.so, got 0x5616c5ab0220
Trying to set dxlevel (111) which is higher than the card can support (110)!
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libmaterialsystem2.so, got 0x5616c5affd10
14.37.21
L 05/24/2024 - 12:37:21: server_cvar: "cash_player_rescued_hostage" "1000"
L 05/24/2024 - 12:37:21: server_cvar: "cash_player_interact_with_hostage" "150"
L 05/24/2024 - 12:37:21: server_cvar: "cash_player_damage_hostage" "-30"
L 05/24/2024 - 12:37:21: server_cvar: "cash_player_killed_hostage" "-1000"
L 05/24/2024 - 12:37:21: server_cvar: "sv_competitive_minspec" "true"
L 05/24/2024 - 12:37:21: server_cvar: "sv_kick_ban_duration" "15.000000"
L 05/24/2024 - 12:37:21: server_cvar: "sv_spec_hear" "1"
L 05/24/2024 - 12:37:21: server_cvar: "mp_c4timer" "40"
L 05/24/2024 - 12:37:21: server_cvar: "mp_roundtime" "5.000000"
L 05/24/2024 - 12:37:21: server_cvar: "mp_team_intro_time" "6.500000"
L 05/24/2024 - 12:37:21: server_cvar: "mp_freezetime" "6"
L 05/24/2024 - 12:37:21: server_cvar: "mp_limitteams" "2"
L 05/24/2024 - 12:37:21: server_cvar: "cash_team_terrorist_win_bomb" "3500"
L 05/24/2024 - 12:37:21: server_cvar: "cash_team_elimination_hostage_map_t" "1000"
L 05/24/2024 - 12:37:21: server_cvar: "cash_team_elimination_hostage_map_ct" "2000"
L 05/24/2024 - 12:37:21: server_cvar: "cash_team_elimination_bomb_map" "3250"
L 05/24/2024 - 12:37:21: server_cvar: "cash_team_win_by_time_running_out_hostage" "3250"
L 05/24/2024 - 12:37:21: server_cvar: "cash_team_win_by_time_running_out_bomb" "3250"
L 05/24/2024 - 12:37:21: server_cvar: "cash_team_win_by_defusing_bomb" "3250"
L 05/24/2024 - 12:37:21: server_cvar: "cash_team_win_by_hostage_rescue" "3500"
L 05/24/2024 - 12:37:21: server_cvar: "cash_team_loser_bonus" "1400"
L 05/24/2024 - 12:37:21: server_cvar: "cash_team_loser_bonus_consecutive_rounds" "500"
L 05/24/2024 - 12:37:21: server_cvar: "sv_teamid_overhead" "true"
L 05/24/2024 - 12:37:21: server_cvar: "mp_autoteambalance" "true"
L 05/24/2024 - 12:37:21: server_cvar: "sv_gravity" "800.000000"
L 05/24/2024 - 12:37:21: server_cvar: "sv_vote_issue_kick_allowed" "true"
L 05/24/2024 - 12:37:21: server_cvar: "sv_vote_kick_ban_duration" "15.000000"
L 05/24/2024 - 12:37:21: server_cvar: "sv_vote_issue_loadbackup_allowed" "true"
Physics Console Communications is not initialized
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libengine2.so, got 0x5616c5a53e80
Loaded /AMP/counter-strike2/730/game/csgo/bin/linuxsteamrt64/libhost.so, got 0x5616c5c175c0
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libscenefilecache.so, got 0x5616c5c2ad80
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libparticles.so, got 0x5616c5c3d0a0
Loaded /AMP/counter-strike2/730/game/csgo/bin/linuxsteamrt64/libmatchmaking.so, got 0x5616c5c50510
[12:37:21.490] CSSharp: Initializing
[12:37:21.490] CSSharp: CoreConfig loaded.
[12:37:21.530] CSSharp: Copying bytes from disk for /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libengine2.so
[12:37:21.683] CSSharp: Copying bytes from disk for /AMP/counter-strike2/730/game/bin/linuxsteamrt64/../../csgo/bin/linuxsteamrt64/libserver.so
[12:37:21.714] CSSharp: Globals loaded.
[12:37:21.721] CSSharp: Failed to find signature for 'Host_Say'
14.37.25
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libengine2.so, got 0x562877ac8e80
Setting breakpad minidump AppID = 2347773
Console initialized.
Steam AppId(730), BreakpadId(2347771)
InitSteamLogin_Internal: Skipping initializing breakpad.
Steam Universe is invalid, possibly asking before Steam was successfully initialized.
ResetBreakpadAppId: Universe is 0 (k_EUniverseInvalid)
ResetBreakpadAppId: Setting dedicated server app id: 2347773
Loaded libSDL3.so.0, got 0x562877b0fb80
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libtier0.so, got 0x562877aaa630
Visibility enabled.
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libfilesystem_stdio.so, got 0x562877b10bb0
USRLOCAL path not found!
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/liblocalize.so, got 0x562877b23340
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/librendersystemempty.so, got 0x562877b23950
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libresourcesystem.so, got 0x562877b244e0
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libschemasystem.so, got 0x562877b25220
Trying to set dxlevel (111) which is higher than the card can support (110)!
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libmaterialsystem2.so, got 0x562877b74d10
14.37.26
L 05/24/2024 - 12:37:26: server_cvar: "cash_player_rescued_hostage" "1000"
L 05/24/2024 - 12:37:26: server_cvar: "cash_player_interact_with_hostage" "150"
L 05/24/2024 - 12:37:26: server_cvar: "cash_player_damage_hostage" "-30"
L 05/24/2024 - 12:37:26: server_cvar: "cash_player_killed_hostage" "-1000"
L 05/24/2024 - 12:37:26: server_cvar: "sv_competitive_minspec" "true"
L 05/24/2024 - 12:37:26: server_cvar: "sv_kick_ban_duration" "15.000000"
L 05/24/2024 - 12:37:26: server_cvar: "sv_spec_hear" "1"
L 05/24/2024 - 12:37:26: server_cvar: "mp_c4timer" "40"
L 05/24/2024 - 12:37:26: server_cvar: "mp_roundtime" "5.000000"
L 05/24/2024 - 12:37:26: server_cvar: "mp_team_intro_time" "6.500000"
L 05/24/2024 - 12:37:26: server_cvar: "mp_freezetime" "6"
L 05/24/2024 - 12:37:26: server_cvar: "mp_limitteams" "2"
L 05/24/2024 - 12:37:26: server_cvar: "cash_team_terrorist_win_bomb" "3500"
L 05/24/2024 - 12:37:26: server_cvar: "cash_team_elimination_hostage_map_t" "1000"
L 05/24/2024 - 12:37:26: server_cvar: "cash_team_elimination_hostage_map_ct" "2000"
L 05/24/2024 - 12:37:26: server_cvar: "cash_team_elimination_bomb_map" "3250"
L 05/24/2024 - 12:37:26: server_cvar: "cash_team_win_by_time_running_out_hostage" "3250"
L 05/24/2024 - 12:37:26: server_cvar: "cash_team_win_by_time_running_out_bomb" "3250"
L 05/24/2024 - 12:37:26: server_cvar: "cash_team_win_by_defusing_bomb" "3250"
L 05/24/2024 - 12:37:26: server_cvar: "cash_team_win_by_hostage_rescue" "3500"
L 05/24/2024 - 12:37:26: server_cvar: "cash_team_loser_bonus" "1400"
L 05/24/2024 - 12:37:26: server_cvar: "cash_team_loser_bonus_consecutive_rounds" "500"
L 05/24/2024 - 12:37:26: server_cvar: "sv_teamid_overhead" "true"
L 05/24/2024 - 12:37:26: server_cvar: "mp_autoteambalance" "true"
L 05/24/2024 - 12:37:26: server_cvar: "sv_gravity" "800.000000"
L 05/24/2024 - 12:37:26: server_cvar: "sv_vote_issue_kick_allowed" "true"
L 05/24/2024 - 12:37:26: server_cvar: "sv_vote_kick_ban_duration" "15.000000"
L 05/24/2024 - 12:37:26: server_cvar: "sv_vote_issue_loadbackup_allowed" "true"
Physics Console Communications is not initialized
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libengine2.so, got 0x562877ac8e80
Loaded /AMP/counter-strike2/730/game/csgo/bin/linuxsteamrt64/libhost.so, got 0x562877c8c5c0
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libscenefilecache.so, got 0x562877c9fd80
Loaded /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libparticles.so, got 0x562877cb20a0
Loaded /AMP/counter-strike2/730/game/csgo/bin/linuxsteamrt64/libmatchmaking.so, got 0x562877cc5510
[12:37:26.427] CSSharp: Initializing
[12:37:26.427] CSSharp: CoreConfig loaded.
[12:37:26.468] CSSharp: Copying bytes from disk for /AMP/counter-strike2/730/game/bin/linuxsteamrt64/libengine2.so
[12:37:26.621] CSSharp: Copying bytes from disk for /AMP/counter-strike2/730/game/bin/linuxsteamrt64/../../csgo/bin/linuxsteamrt64/libserver.so
[12:37:26.653] CSSharp: Globals loaded.
[12:37:26.660] CSSharp: Failed to find signature for 'Host_Say'
[Generic Warning/12]   : The application stopped unexpectedly. Exit code 139
`
The final error line, may be from AMP.

**Comment by gabrielsdelima75** [comment] 2024-05-25 04:55
partially resolved https://nightly.link/roflmuffin/CounterStrikeSharp/actions/runs/9218764462/counterstrikesharp-build-linux-fdbbcad.zip

**Comment by zonical** [comment] 2024-05-25 09:12
Rolfmuffin has released a patch - v234. Not all of the offsets have been tested, so if any more issues arise, please create a new request. Ngā mihi nui.

**Closed by zonical** 2024-05-25 09:12 UTC
Labels: untriaged
