### ISSUE TITLE
[BUG]: `ConVar.Find` reading multiline string

### ISSUE THREAD

**Issue by kus** [roflmuffin/CounterStrikeSharp#111] opened 2023-11-22 05:30 UTC
I'm trying to read and parse the output of `print_mapgroup_sv` but it is `null`.

Output from my server console:

```
] print_mapgroup_sv
Map group: mg_active
	   de_inferno
	   de_train
	   de_mirage
	   de_nuke
	   de_dust2
	   de_overpass
	   de_vertigo
] css_mapgroup
[CS2Maps] print_mapgroup_sv is null!
```

With the following code:

```
var mapgroupCvar = ConVar.Find("print_mapgroup_sv");
if (mapgroupCvar is null)
{
    Logger.LogInformation("print_mapgroup_sv is null!");
}
else
{
    Logger.LogInformation($"print_mapgroup_sv = {mapgroupCvar.StringValue}");
}
```

**Comment by Poggicek** [comment] 2023-11-22 06:09
It's a command and not a convar, there can't be a any value stored

**Comment by kus** [comment] 2023-11-22 06:10
Okay, is there a way to read the output of `print_mapgroup_sv`?

**Comment by kus** [comment] 2023-11-22 06:12
My server has multiple mods on it which I control the maps by changing the mapgroup when the mod changes. So I want a way to read the current maps in the mapgroup.

**Comment by roflmuffin** [comment] 2023-11-24 11:08
We cannot currently read output of commands, so I am going to close this as technically not a bug. You could create a feature enhancement as `Add support for reading command output` if you wish to track that.

**Closed by roflmuffin** 2023-11-24 11:08 UTC
